# Generated by Django 5.0.2 on 2024-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='book',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
